FinalProject_RedditClone/Controllers/ReportController.cs
using FinalProject_RedditClone.Utility.Repositories;
using FinalProject_RedditClone.Utility.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject_RedditClone.Controllers
{
    public class ReportController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ReportController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var posts = _unitOfWork.Posts.GetAll();
            var comments = _unitOfWork.Comment.GetAll();
            var forums = _unitOfWork.Forum.GetAll();
            var votes = _unitOfWork.Vote.GetAll();
            /*var postComments = _unitOfWork.Comment.GetAllByPostId()*/

            var vm = new ReportingVM()
            {
                Posts = posts,
                Comments = comments,
                Forums = forums,
                Votes = votes
            };

            return View(vm);
        }
    }
}

FinalProject_RedditClone/Controllers/UserController.cs
using FinalProject_RedditClone.Models;
using FinalProject_RedditClone.Utility.Repositories;
using FinalProject_RedditClone.Utility.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using System.Security.Claims;
using System.Xml.Linq;

namespace FinalProject_RedditClone.Controllers
{
    
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        public UserController(IUnitOfWork unitOfWork, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var users = _unitOfWork.User.GetUsers();
            return View(users);
        }

        [Authorize(Roles = "Admin, Contributor")]
        public async Task<IActionResult> Edit(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                id = GetCurrentUserId();
            }

            var user = _unitOfWork.User.GetUser(id);
            var roles = _unitOfWork.Role.GetRoles();

            var userRoles = await _signInManager.UserManager.GetRolesAsync(user);

            var roleItems = roles.Select(role =>
                new SelectListItem(
                    role.Name,
                    role.Id,
                    userRoles.Any(ur => ur.Contains(role.Name)))).ToList();

            var vm = new EditUserVM
            {
                User = user,
                Roles = roleItems,
                ProfilePicture = null
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> OnPostAsync(EditUserVM data)
        {
            var user = _unitOfWork.User.GetUser(data.User.Id);
            if (user == null)
            {
                return NotFound();
            }

            var userRolesInDb = await _signInManager.UserManager.GetRolesAsync(user);

            var rolesToAdd = new List<string>();
            var rolesToDelete = new List<string>();
            

            if(data.Roles != null)
            {
                foreach (var role in data.Roles)
                {
                    var assignedInDb = userRolesInDb.FirstOrDefault(ur => ur == role.Text);
                    if (role.Selected)
                    {
                        if (assignedInDb == null)
                        {
                            rolesToAdd.Add(role.Text);
                        }
                    }
                    else
                    {
                        if (assignedInDb != null)
                        {
                            rolesToDelete.Add(role.Text);
                        }
                    }
                }
            }
            

            if (rolesToAdd.Any())
            {
                await _signInManager.UserManager.AddToRolesAsync(user, rolesToAdd);
            }

            if (rolesToDelete.Any())
            {
                await _signInManager.UserManager.RemoveFromRolesAsync(user, rolesToDelete);
            }

            user.FirstName = data.User.FirstName;
            user.LastName = data.User.LastName;
            user.Email = data.User.Email;
            user.PhoneNumber = data.User.PhoneNumber;

            if(data.ProfilePicture != null && data.ProfilePicture.Length > 0)
            {
                var memoryStream = new MemoryStream();
                await data.ProfilePicture.CopyToAsync(memoryStream);
                user.ProfilePicture = memoryStream.ToArray();
            }

            _unitOfWork.User.UpdateUser(user);

            return RedirectToAction("Edit", new { id = user.Id });
        }

        public async Task<IActionResult> GetProfilePicture(string id)
        {
            var user =  _unitOfWork.User.GetUser(id);
            if(user == null)
            {
                return NotFound();
            }

            var imgData = user.ProfilePicture;
            return File(imgData, "image/jpg");
        }

        private string GetCurrentUserId()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            return userId;
        }
    }
}

FinalProject_RedditClone/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SpeakEasy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-utilities.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalProject_RedditClone.styles.css" asp-append-version="true" />
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom -->
    <link href="css/custom.css" rel="stylesheet">
    <link href="~/css/custom.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->

    <!-- fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/font-awesome-4.0.3/css/font-awesome.min.css">

    <!-- CSS STYLE-->
    <link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />

    <!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="rs-plugin/css/settings.css" media="screen" />
</head>
<body>
    <header>
        <div class="headernav">
            <div class="container">
                <div class="row">
                    <div class="col-lg-1 col-xs-3 col-sm-2 col-md-2 logo ">
                        <h2 class=""><a class="" asp-controller="Home" asp-action="Index">SpeakEasy</a></h2>
                    </div>
                    <div class="col-lg-3 col-xs-9 col-sm-5 col-md-3 selecttopic">
                        <div class="dropdown">
                            @*Add forum ddl here*@
                        </div>
                    </div>
                    <div class="col-lg-4 search hidden-xs hidden-sm col-md-3">
                        <div class="wrap">
                            @using (Html.BeginForm("Index", "Home", FormMethod.Get))
                            {
                                <div class="pull-left txt"><input type="text" class="form-control" placeholder="Search Topics" name="searchString"></div>
                                <div class="pull-right"><button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button></div>
                                <div class="clearfix"></div>
                            }
                        </div>
                    </div>
                    <div class="col-lg-4 col-xs-12 col-sm-5 col-md-4 avt">
                        <div class="stnt pull-left">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <div class="stnt pull-left">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        Profile
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a asp-controller="User" asp-action="Edit">View Profile</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li>
                                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                            </form>
                                        </li>
                                        @*<li><a asp-controller="Report" asp-action="Index">Reports</a></li>*@
                                    </ul>
                                </div>
                            }
                            else
                            {
                                <div class="stnt pull-left">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        Login
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li class="nav-item">
                                            <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Register</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Login">Login</a>
                                        </li>
                                    </ul>
                                </div>
                            }
                        </div>
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="stnt pull-right">
                                <form class="form-inline" asp-controller="Report" asp-action="Index">
                                    <button type="submit" class="btn btn-primary">Reports</button>
                                </form>
                            </div>
                        }
                        
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <br />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-1 col-xs-3 col-sm-2 logo "><a href="#"><img src="images/logo.jpg" alt="" /></a></div>
                <div class="col-lg-8 col-xs-9 col-sm-5 ">Copyrights 2023, SpeakEasyMIS421.com</div>
                <div class="col-lg-3 col-xs-12 col-sm-5 sociconcent">
                    <ul class="socialicons">
                        <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-cloud"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.js"></script>
    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="~/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="~/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/lib/bootsrap/dist/js/bootstrap.min.js"></script>


    <!-- LOOK THE DOCUMENTATION FOR MORE INFORMATIONS -->
    <script type="text/javascript">

        var revapi;

        jQuery(document).ready(function () {
            "use strict";
            revapi = jQuery('.tp-banner').revolution(
                {
                    delay: 15000,
                    startwidth: 1200,
                    startheight: 278,
                    hideThumbs: 10,
                    fullWidth: "on"
                });

        });	//ready

    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/jsOriginal/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>