FinalProject_RedditClone/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject_RedditClone.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AppRolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public AppRolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            if(!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }
    }
}

FinalProject_RedditClone/Controllers/HomeController.cs
using FinalProject_RedditClone.Models;
using FinalProject_RedditClone.Utility.Repositories;
using FinalProject_RedditClone.Utility.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System.Diagnostics;

namespace FinalProject_RedditClone.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        public IActionResult Index(string searchString)
        {
            var model = new HomeFeedVM();
            var userId = _userManager.GetUserId(HttpContext.User);
            model.Forums = _unitOfWork.Forum.GetAll();
            model.Comments = _unitOfWork.Comment.GetAll();
            model.Votes = _unitOfWork.Vote.GetAll();
            
            if (String.IsNullOrEmpty(searchString))
            {
                model.Posts = _unitOfWork.Posts.GetHomeFeed();
            }
            else
            {
                model.Posts = _unitOfWork.Posts.SearchPosts(searchString);
                model.SearchString = searchString;
            }

            if(userId != null)
            {
                model.User = _unitOfWork.User.GetUser(userId);
            }

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinalProject_RedditClone/Controllers/UserController.cs
using FinalProject_RedditClone.Models;
using FinalProject_RedditClone.Utility.Repositories;
using FinalProject_RedditClone.Utility.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using System.Security.Claims;
using System.Xml.Linq;

namespace FinalProject_RedditClone.Controllers
{
    
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        public UserController(IUnitOfWork unitOfWork, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var users = _unitOfWork.User.GetUsers();
            return View(users);
        }

        [Authorize(Roles = "Admin, Contributor")]
        public async Task<IActionResult> Edit(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                id = GetCurrentUserId();
            }

            var user = _unitOfWork.User.GetUser(id);
            var roles = _unitOfWork.Role.GetRoles();

            var userRoles = await _signInManager.UserManager.GetRolesAsync(user);

            var roleItems = roles.Select(role =>
                new SelectListItem(
                    role.Name,
                    role.Id,
                    userRoles.Any(ur => ur.Contains(role.Name)))).ToList();

            var vm = new EditUserVM
            {
                User = user,
                Roles = roleItems,
                ProfilePicture = null
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> OnPostAsync(EditUserVM data)
        {
            var user = _unitOfWork.User.GetUser(data.User.Id);
            if (user == null)
            {
                return NotFound();
            }

            var userRolesInDb = await _signInManager.UserManager.GetRolesAsync(user);

            var rolesToAdd = new List<string>();
            var rolesToDelete = new List<string>();
            

            if(data.Roles != null)
            {
                foreach (var role in data.Roles)
                {
                    var assignedInDb = userRolesInDb.FirstOrDefault(ur => ur == role.Text);
                    if (role.Selected)
                    {
                        if (assignedInDb == null)
                        {
                            rolesToAdd.Add(role.Text);
                        }
                    }
                    else
                    {
                        if (assignedInDb != null)
                        {
                            rolesToDelete.Add(role.Text);
                        }
                    }
                }
            }
            

            if (rolesToAdd.Any())
            {
                await _signInManager.UserManager.AddToRolesAsync(user, rolesToAdd);
            }

            if (rolesToDelete.Any())
            {
                await _signInManager.UserManager.RemoveFromRolesAsync(user, rolesToDelete);
            }

            user.FirstName = data.User.FirstName;
            user.LastName = data.User.LastName;
            user.Email = data.User.Email;
            user.PhoneNumber = data.User.PhoneNumber;

            if(data.ProfilePicture != null && data.ProfilePicture.Length > 0)
            {
                var memoryStream = new MemoryStream();
                await data.ProfilePicture.CopyToAsync(memoryStream);
                user.ProfilePicture = memoryStream.ToArray();
            }

            _unitOfWork.User.UpdateUser(user);

            return RedirectToAction("Edit", new { id = user.Id });
        }

        public async Task<IActionResult> GetProfilePicture(string id)
        {
            var user =  _unitOfWork.User.GetUser(id);
            if(user == null)
            {
                return NotFound();
            }

            var imgData = user.ProfilePicture;
            return File(imgData, "image/jpg");
        }

        private string GetCurrentUserId()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            return userId;
        }
    }
}

FinalProject_RedditClone/Views/Home/Index - Original.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FinalProject_RedditClone/Views/Home/Index.cshtml
@using FinalProject_RedditClone.Utility.ViewModels;
@model HomeFeedVM

@{
    ViewData["Title"] = "Home Page";
}

    <body>
        <div class="container-fluid" id="content">

            @if (User.Identity.IsAuthenticated)
            {
                <div class="container">
                    <div class="row pull-left">
                        <div class="col">
                            <form>
                                <button class="btn btn-primary" asp-controller="Posts" asp-action="Create">New Post</button>
                            </form>
                        </div>
                        <div class="col">
                            <form>
                                <button class="btn btn-primary" asp-controller="Forum" asp-action="Create">New Forum</button>
                            </form>
                        </div>
                        
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="col">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </button>
                                <ul class="dropdown-menu">
                                    <li class="nav-item"><a class="dropdown-item" asp-area="" asp-controller="AppRoles" asp-action="Index">Roles</a></li>
                                    <li class="nav-item"><a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Users</a></li>
                                </ul>
                            </div>
                        }
                    </div>
                </div>
                <br />
            }
        
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-8">

                            @foreach(var post in Model.Posts)
                            {
                                int commentCount = 0;
                                foreach (var comment in Model.Comments)
                                {
                                    if (comment.PostId == post.Id)
                                    {
                                        commentCount++;
                                    }
                                }

                                <div class="post">
                                    <div class="wrap-ut pull-left">
                                        <div class="userinfo pull-left">
                                            <div class="avatar">
                                                <img src="@Url.Action("GetProfilePicture", "User", new {Id = post.UserId})" width="50" height="50" />
                                                @*<div class="status green">&nbsp;</div>*@
                                            </div>

                                            <div class="icons">
                                                <img src="images/icon1.jpg" alt="" /><img src="images/icon4.jpg" alt="" />
                                            </div>
                                        </div>
                                        <div class="posttext pull-left">
                                            <h2><a asp-controller="Posts" asp-action="Details" asp-route-id="@post.Id">@post.Title</a></h2>
                                            <p>@post.Content</p>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="postinfo pull-left">
                                        <div class="comments">
                                            <div class="commentbg">
                                                @commentCount
                                                <div class="mark"></div>
                                            </div>

                                        </div>
                                        @*<div class="views"><i class="fa fa-eye"></i> 1,568</div>
                                        <div class="time"><i class="fa fa-clock-o"></i> 24 min</div>*@
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            }
                           
                        </div>

                        <div class="col-lg-4 col-md-4">

                            <!-- -->
                            <div class="sidebarblock">
                                <h3>Top Forums</h3>
                                <div class="divline"></div>
                                <div class="blocktxt">
                                    <ul class="cats">
                                        @foreach (var forum in Model.Forums)
                                        {
                                            var postCount = 0;
                                            @foreach(var post in Model.Posts)
                                            {
                                                if(post.ForumId == forum.Id)
                                                {
                                                    postCount++;
                                                }
                                            }
                                            <li><a asp-controller="Forum" asp-action="Details" asp-route-id="@forum.Id">@forum.Title <span class="badge pull-right">@postCount</span></a></li>
                                        }
                                    </ul>
                                </div>
                            </div>
                            
                            @if(User.Identity.IsAuthenticated)
                            {
                                <div class="sidebarblock">
                                    <h3>Liked Forums</h3>
                                    <div class="divline"></div>
                                    <div class="blocktxt">
                                        <ul class="cats">
                                            @foreach (var forum in Model.Forums)
                                            {
                                                @foreach(var vote in Model.Votes)
                                                {
                                                    if (vote.ForumId == forum.Id && vote.UserId == Model.User.Id)
                                                    {
                                                        var postCount = 0;
                                                        @foreach(var post in Model.Posts)
                                                        {
                                                            if(post.ForumId == forum.Id)
                                                            {
                                                                postCount++;
                                                            }
                                                        }
                                                        <li><a asp-controller="Forum" asp-action="Details" asp-route-id="@forum.Id">@forum.Title <span class="badge pull-right">@postCount</span></a></li>
                                                    }
                                                }
                                            }
                                        </ul>
                                    </div>
                                </div>
                            }
                            
                        </div>
                    </div>
                </div>



                @*<div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-xs-12">
                            <div class="pull-left"><a href="#" class="prevnext"><i class="fa fa-angle-left"></i></a></div>
                            <div class="pull-left">
                                <ul class="paginationforum">
                                    <li class="hidden-xs"><a href="#">1</a></li>
                                    <li class="hidden-xs"><a href="#">2</a></li>
                                    <li class="hidden-xs"><a href="#">3</a></li>
                                    <li class="hidden-xs"><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li><a href="#">6</a></li>
                                    <li><a href="#" class="active">7</a></li>
                                    <li><a href="#">8</a></li>
                                    <li class="hidden-xs"><a href="#">9</a></li>
                                    <li class="hidden-xs"><a href="#">10</a></li>
                                    <li class="hidden-xs hidden-md"><a href="#">11</a></li>
                                    <li class="hidden-xs hidden-md"><a href="#">12</a></li>
                                    <li class="hidden-xs hidden-sm hidden-md"><a href="#">13</a></li>
                                    <li><a href="#">1586</a></li>
                                </ul>
                            </div>
                            <div class="pull-left"><a href="#" class="prevnext last"><i class="fa fa-angle-right"></i></a></div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>*@
        </div>
    </body>